export { default as UButton } from './button/button.vue'
export { default as UInput } from './input/input.vue'
export { default as UAvatar } from './avatar/avatar.vue'
export { default as UBadge } from './badge/badge.vue'
export { default as UMenu } from './menu/menu.vue'
export { default as ULoader } from './loader/loader.vue'
export { default as UPopover } from './popover/popover.vue'
export { default as USteps } from './steps/steps.vue'
